version: '3.9'
services:
  postgresql:
    image: postgres
    container_name: courses
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DATABASE=diplom
    command: postgres
    restart: always
