services:
  postgresql:
    image: postgres
    container_name: courses
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=diplom
    command: postgres
    restart: always
